version: '3'
services:
  database:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_DATABASE=ums_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      test_network_ums:
        aliases:
        - database
  app:
    build: .
    ports:
    - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/ums_db
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SMTP_HOST=<SMTP_HOST>
    - SMTP_PORT=<SMTP_PORT>
    - SMTP_USERNAME=<SMTP_USERNAME>
    - SMTP_PASSWORD=<SMTP_PASSWORD>
    - SMTP_FROM=<SMTP_FROM>
    depends_on:
      - database
    networks:
      test_network_ums:
        aliases:
          - app
networks:
  test_network_ums:
